name: frogs_weather_v2
description: Application météo complète avec prévisions, fond dynamique et alertes météo

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  geolocator: ^14.0.1
  intl: ^0.20.2
  provider: ^6.1.2
  flutter_local_notifications: ^19.3.0
  logger: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
